/* Banco */
/***********************************************************************************************************************/

CREATE DATABASE ProjectPay;
USE ProjectPay;

/***********************************************************************************************************************/

/* Tabelas */
/***********************************************************************************************************************/

CREATE TABLE IF NOT EXISTS USUARIO (
	ID INT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(250) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	CRIADO DATETIME,
	ATIVO INT(1) NOT NULL,
    CONSTRAINT PRK_ID_USUARIO PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USUARIO_PADRAO (
	ID INT NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	NOME_COMPLETO VARCHAR(250) NOT NULL,
    CONSTRAINT PRK_CPF_USUARIO PRIMARY KEY (CPF),
	CONSTRAINT FRK_ID_USUARIO FOREIGN KEY (ID) REFERENCES USUARIO(ID)
);

CREATE TABLE IF NOT EXISTS USUARIO_LOJISTA (
	ID INT NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	RAZAO_SOCIAL VARCHAR(250) NOT NULL,
    CONSTRAINT PRK_CNPJ_LOJISTA PRIMARY KEY (CNPJ),
	CONSTRAINT FRK_ID_LOJISTA FOREIGN KEY (ID) REFERENCES USUARIO(ID)
);

CREATE TABLE IF NOT EXISTS CARTEIRA (
	ID INT NOT NULL AUTO_INCREMENT,
	USUARIO INT NOT NULL,
	SALDO DECIMAL(15,2) NOT NULL,
    CONSTRAINT PRK_CARTEIRA PRIMARY KEY (ID),
	CONSTRAINT FRK_CARTEIRA_USUARIO FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE IF NOT EXISTS STATUS_TRANSACAO (
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(250) NOT NULL,
    CONSTRAINT PRK_STATUS_TRANSACAO PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TRANSACAO (
	ID INT NOT NULL AUTO_INCREMENT,
	DATA DATETIME,
	ORIGEM INT NOT NULL,
	DESTINO INT NOT NULL,
	VALOR DECIMAL(15,2) NOT NULL,
	STATUS INT NOT NULL,
    CONSTRAINT PRK_TRANSACAO PRIMARY KEY (ID),
	CONSTRAINT FRK_TRANSACAO_ORIGEM FOREIGN KEY (ORIGEM) REFERENCES CARTEIRA(ID),
	CONSTRAINT FRK_TRANSACAO_DESTINO FOREIGN KEY (DESTINO) REFERENCES CARTEIRA(ID),
	CONSTRAINT FRK_TRANSACAO_STATUS FOREIGN KEY (STATUS) REFERENCES STATUS_TRANSACAO(ID)
);

/***********************************************************************************************************************/

INSERT INTO USUARIO (EMAIL, SENHA, CRIADO, ATIVO) VALUES ('anderson@email.com', PASSWORD('minhasenha123'), SYSDATE(), 1);
INSERT INTO USUARIO (EMAIL, SENHA, CRIADO, ATIVO) VALUES ('salao.cabeleireira@email.com', PASSWORD('12senha34'), SYSDATE(), 1);

INSERT INTO USUARIO_PADRAO (ID, CPF, NOME_COMPLETO) VALUES (1, '98765432100', 'ANDERSON COSTA');
INSERT INTO USUARIO_LOJISTA (ID, CNPJ, RAZAO_SOCIAL) VALUES (2, '12345678901234', 'SALÃO CABELEIREIRA');

INSERT INTO CARTEIRA (USUARIO, SALDO) VALUES (1, '500.00');
INSERT INTO CARTEIRA (USUARIO, SALDO) VALUES (2, '1000.00');

INSERT INTO STATUS_TRANSACAO (DESCRICAO) VALUES ('Em análise');
INSERT INTO STATUS_TRANSACAO (DESCRICAO) VALUES ('Autorizado');
INSERT INTO STATUS_TRANSACAO (DESCRICAO) VALUES ('Enviado');
INSERT INTO STATUS_TRANSACAO (DESCRICAO) VALUES ('Não Autorizado');
INSERT INTO STATUS_TRANSACAO (DESCRICAO) VALUES ('Cancelado');